### ISSUE TITLE
这个系统是因果的吗？可以实时处理吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [ZhongshuHou/MHA-DPCRN#1]
你好
      从 这里看 https://github.com/Qinwen-Hu/dparn#experimental-results  你这个结果 要比DPCRN好蛮多，因为没找到你的论文，不知道是否满足因果 和 实时处理，计算量大不大?
![image](https://user-images.githubusercontent.com/3354428/177078358-8d04719b-33fb-494e-af8e-8a26789faed8.png)

谢谢！

**Comment by ZhongshuHou** [comment]
你好
&nbsp; &nbsp; &nbsp;这是关于这部分工作的文章，可以参考一下，应该能回答你的问题。
&nbsp; &nbsp; &nbsp;2206.14524.pdf (arxiv.org)
&nbsp; &nbsp; &nbsp;2206.13136.pdf (arxiv.org)
侯仲舒
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Jul 4, 2022 11:51 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[ZhongshuHou/MHA-DPCRN] 这个系统是因果的吗？可以实时处理吗？ (Issue #1)

&nbsp;



 
你好
 从 这里看 https://github.com/Qinwen-Hu/dparn#experimental-results  你这个结果 要比DPCRN好蛮多，因为没没到你的论文，不知道是否满足因果 和 实时处理，计算量大不大?
 
 
谢谢！

**Comment by zuowanbushiwo** [comment]
谢谢你的回答，上面的有一些乱码。
<img width="547" alt="image" src="https://user-images.githubusercontent.com/3354428/177095441-1e455936-fb56-49a6-8c11-caf5909ca8f9.png">

2206.13136.pdf ：A two-stage full-band speech enhancement model with effective spectral compression mapping
2206.14524.pdf ：A light-weight full-band speech enhancement model
对吗？

我对attention 机制目前还不太理解，这个可以像 DPCRN 那样可以做frame-by-frame的实时推理方式？attention 不会用到未来的信息吗？
<img width="556" alt="image" src="https://user-images.githubusercontent.com/3354428/177095964-96e44811-a0e1-42a9-b688-228c1cb62521.png">
<img width="566" alt="image" src="https://user-images.githubusercontent.com/3354428/177096057-e272a67e-8e8b-4a2c-ae5a-d9e2b8c54fe4.png">

**Comment by zuowanbushiwo** [comment]
这两篇文章都只有参数的大小，没有计算量的对比。这个对比原版的DPCRN，计算量提升大吗？
我看[README](https://github.com/Le-Xiaohuai-speech/DPCRN_DNS3/tree/main/inference/real_time_inference)，DPCRN的tflite 版本是 1.1 G MACs

**Comment by ZhongshuHou** [comment]
attention是可以做到保证因果性，实时推理的，可以参照以下文章
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Jul 4, 2022 02:41 PM
To: ***@***.***&gt;; 
Cc: &nbsp;"Zhongshu ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ZhongshuHou/MHA-DPCRN] 这个系统是因果的吗？可以实时处理吗？ (Issue #1)

&nbsp;



 
谢谢你的回答，上面的有一些乱码。
 
 
2206.13136.pdf ：A two-stage full-band speech enhancement model with effective spectral compression mapping
 2206.14524.pdf ：A light-weight full-band speech enhancement model
 
我对attention 机制目前还不太理解，这个可以像 DPCRN 那样可以做实时推理吗？attention 不会用到未来的信息吗？

**Comment by ZhongshuHou** [comment]
这是全频带DNS比赛中的冠军模型，你也可以参考一下
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Jul 4, 2022 02:56 PM
To: ***@***.***&gt;; 
Cc: &nbsp;"Zhongshu ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ZhongshuHou/MHA-DPCRN] 这个系统是因果的吗？可以实时处理吗？ (Issue #1)

&nbsp;



 
这两篇文章都只有参数的大小，没有计算量的对比。这个对比原版的DPCRN，计算量提升大吗？
 我看README，DPCRN的tflite 版本是 1.1 G MACs

**Comment by zuowanbushiwo** [comment]
(1) 你还会完善这个项目吗？可以添加一些实时推理的脚本吗？像实际的语音信号处理系统那样，一帧一帧的做推理。
(2) SpecCompress.npy 是怎么生成的？
祝身体健康，工作顺利
谢谢

**Comment by ZhongshuHou** [comment]
(1) 因为我现在是在读研究生，可能没有时间把这个项目做成完全流式的落地系统了。
(2) 这个生成方式在dparn的论文中有详细地描述，可以自己实现。&nbsp;
&nbsp;谢谢
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Jul 4, 2022 05:04 PM
To: ***@***.***&gt;; 
Cc: &nbsp;"Zhongshu ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ZhongshuHou/MHA-DPCRN] 这个系统是因果的吗？可以实时处理吗？ (Issue #1)

&nbsp;



 
(1) 你还会完善这个项目吗？可以添加一些实时推理的脚本吗？像实际的语音信号处理系统那样，一帧一帧的做推理。
 (2) SpecCompress.npy 是怎么生成的？
 祝身体健康，工作顺利
 谢谢

**Comment by zuowanbushiwo** [comment]
好的，感谢！

**Comment by ZhongshuHou** [comment]
DPARN的运算量大约是5 G MACs，DPARN是用于处理全频带语音的（48kHz采样），跟用于处理宽带语音（16kHz采样，DPCRN最初提出也是在宽带处理的情景）模型是有差别的，因为语音采样率变高了，需要处理的特征信息也多了，所以原运算量也是有提升的。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Jul 4, 2022 02:56 PM
To: ***@***.***&gt;; 
Cc: &nbsp;"Zhongshu ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ZhongshuHou/MHA-DPCRN] 这个系统是因果的吗？可以实时处理吗？ (Issue #1)

&nbsp;



 
这两篇文章都只有参数的大小，没有计算量的对比。这个对比原版的DPCRN，计算量提升大吗？
 我看README，DPCRN的tflite 版本是 1.1 G MACs

**Comment by andyye1999** [comment]
期待可以做成流式推理
